name: "Deploy Cloud Functions"
description: "Action to deploy cloud functions"
inputs:
  function_name:
    description: 'Cloud Function Name'
    required: true
  entry_point:
    description: 'Cloud Function Entry Point'
    required: true
  runtime:
    description: 'Cloud Function Runtime'
    required: true
  description:
    description: 'Cloud Function Description'
    required: true
  region:
    description: 'Cloud Function Region'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Code To Deploy
      # デプロイ対象となる関数をルートディレクトリにコピーする
      run: cp internal/interface/cloudfunctions/*.go ./
      shell: bash
    # SEE: https://github.com/google-github-actions/deploy-cloud-functions
    - id: "deploy"
      shell: bash
      # https://cloud.google.com/sdk/gcloud/reference/functions/deploy
      run: |
        gcloud functions deploy ${{ inputs.function_name }} \
          --entry-point=${{ inputs.entry_point }} \
          --runtime=${{ inputs.runtime }} \
          --gen2 \
          --region=${{ inputs.region }} \
          --trigger-http
    - id: "describe"
      # https://cloud.google.com/sdk/gcloud/reference/functions/describe
      run: |
        gcloud functions describe ${{ inputs.function_name }} \
          --region=${{ inputs.region }}
      shell: bash