name: "Deploy Cloud Functions"
description: "Action to deploy cloud functions"
inputs:
  function_name:
    description: 'Cloud Function Name'
    required: true
  entry_point:
    description: 'Cloud Function Entry Point'
    required: true
  runtime:
    description: 'Cloud Function Runtime'
    required: true
  description:
    description: 'Cloud Function Description'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Code To Deploy
      # デプロイ対象となる関数をルートディレクトリにコピーする
      run: cp internal/interface/cloudfunctions/*.go ./
      shell: bash
    # SEE: https://github.com/google-github-actions/deploy-cloud-functions
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: ${{ inputs.function_name }}
        entry_point: ${{ inputs.entry_point }}
        runtime: ${{ inputs.runtime }}
        description: ${{ inputs.description }}
    - id: 'describe'
      run: gcloud functions describe ${{ inputs.function_name }}
      shell: bash