name: "Deploy Cloud Functions"
description: "Action to deploy cloud functions"
inputs:
  google_credentials_json:
    description: 'Google Service Account Credential'
    required: true
  google_cloud_project_id:
    description: 'Google Cloud Project ID'
    required: true
  function_name:
    description: 'Cloud Function Name'
    required: true
  entry_point:
    description: 'Cloud Function Entry Point'
    required: true
  runtime:
    description: 'Cloud Function Runtime'
    required: true
  description:
    description: 'Cloud Function Description'
    required: true
  reigon:
    description: 'Cloud Function Reign'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Code To Deploy
      # デプロイ対象となる関数をルートディレクトリにコピーする
      run: cp internal/interface/cloudfunctions/*.go ./
      shell: bash
    # SEE: https://github.com/google-github-actions/deploy-cloud-functions
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ inputs.google_credentials_json }}
    - name: 'Setup gcloud CLI'
      uses: 'google-github-actions/setup-gcloud@v0.2.0'
      with:
        project_id: ${{ inputs.google_cloud_project_id }}
        service_account_key: ${{ inputs.google_credentials_json }}
    - id: 'deploy'
      shell: bash
      run: >-
        gcloud functions deploy ${{ inputs.function_name }}
        --gen2
        --runtime=${{ inputs.runtime }}
        --region=${{ inputs.region }}
        --source=.
        --entry-point=${{ inputs.entry_point }}
        --trigger-http
        --no-allow-unauthenticated
        --set-env-vars GCP_PROJECT=${{ inputs.google_cloud_project_id }}
    - id: 'describe'
      run: gcloud functions describe ${{ inputs.function_name }}
      shell: bash