name: "Setup go environment"
description: "set up go and install libraries"
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22
    - name: Install dependencies
      shell: bash
      run: go mod tidy
