// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

var TableNames = struct {
	GooglePlaceOpeningPeriods          string
	GooglePlacePhotoAttributions       string
	GooglePlacePhotoReferences         string
	GooglePlacePhotos                  string
	GooglePlaceReviews                 string
	GooglePlaceTypes                   string
	GooglePlaces                       string
	Places                             string
	PlanCandidatePlaces                string
	PlanCandidateSetLikePlaces         string
	PlanCandidateSetMetaData           string
	PlanCandidateSetMetaDataCategories string
	PlanCandidateSetSearchedPlaces     string
	PlanCandidateSets                  string
	PlanCandidates                     string
	Users                              string
}{
	GooglePlaceOpeningPeriods:          "google_place_opening_periods",
	GooglePlacePhotoAttributions:       "google_place_photo_attributions",
	GooglePlacePhotoReferences:         "google_place_photo_references",
	GooglePlacePhotos:                  "google_place_photos",
	GooglePlaceReviews:                 "google_place_reviews",
	GooglePlaceTypes:                   "google_place_types",
	GooglePlaces:                       "google_places",
	Places:                             "places",
	PlanCandidatePlaces:                "plan_candidate_places",
	PlanCandidateSetLikePlaces:         "plan_candidate_set_like_places",
	PlanCandidateSetMetaData:           "plan_candidate_set_meta_data",
	PlanCandidateSetMetaDataCategories: "plan_candidate_set_meta_data_categories",
	PlanCandidateSetSearchedPlaces:     "plan_candidate_set_searched_places",
	PlanCandidateSets:                  "plan_candidate_sets",
	PlanCandidates:                     "plan_candidates",
	Users:                              "users",
}
