// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testGooglePlacePhotos(t *testing.T) {
	t.Parallel()

	query := GooglePlacePhotos()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testGooglePlacePhotosDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := GooglePlacePhotos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGooglePlacePhotosQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := GooglePlacePhotos().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := GooglePlacePhotos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGooglePlacePhotosSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GooglePlacePhotoSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := GooglePlacePhotos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGooglePlacePhotosExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := GooglePlacePhotoExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if GooglePlacePhoto exists: %s", err)
	}
	if !e {
		t.Errorf("Expected GooglePlacePhotoExists to return true, but got false.")
	}
}

func testGooglePlacePhotosFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	googlePlacePhotoFound, err := FindGooglePlacePhoto(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if googlePlacePhotoFound == nil {
		t.Error("want a record, got nil")
	}
}

func testGooglePlacePhotosBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = GooglePlacePhotos().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testGooglePlacePhotosOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := GooglePlacePhotos().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testGooglePlacePhotosAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	googlePlacePhotoOne := &GooglePlacePhoto{}
	googlePlacePhotoTwo := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, googlePlacePhotoOne, googlePlacePhotoDBTypes, false, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}
	if err = randomize.Struct(seed, googlePlacePhotoTwo, googlePlacePhotoDBTypes, false, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = googlePlacePhotoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = googlePlacePhotoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := GooglePlacePhotos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testGooglePlacePhotosCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	googlePlacePhotoOne := &GooglePlacePhoto{}
	googlePlacePhotoTwo := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, googlePlacePhotoOne, googlePlacePhotoDBTypes, false, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}
	if err = randomize.Struct(seed, googlePlacePhotoTwo, googlePlacePhotoDBTypes, false, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = googlePlacePhotoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = googlePlacePhotoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := GooglePlacePhotos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func googlePlacePhotoBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *GooglePlacePhoto) error {
	*o = GooglePlacePhoto{}
	return nil
}

func googlePlacePhotoAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *GooglePlacePhoto) error {
	*o = GooglePlacePhoto{}
	return nil
}

func googlePlacePhotoAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *GooglePlacePhoto) error {
	*o = GooglePlacePhoto{}
	return nil
}

func googlePlacePhotoBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *GooglePlacePhoto) error {
	*o = GooglePlacePhoto{}
	return nil
}

func googlePlacePhotoAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *GooglePlacePhoto) error {
	*o = GooglePlacePhoto{}
	return nil
}

func googlePlacePhotoBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *GooglePlacePhoto) error {
	*o = GooglePlacePhoto{}
	return nil
}

func googlePlacePhotoAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *GooglePlacePhoto) error {
	*o = GooglePlacePhoto{}
	return nil
}

func googlePlacePhotoBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *GooglePlacePhoto) error {
	*o = GooglePlacePhoto{}
	return nil
}

func googlePlacePhotoAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *GooglePlacePhoto) error {
	*o = GooglePlacePhoto{}
	return nil
}

func testGooglePlacePhotosHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &GooglePlacePhoto{}
	o := &GooglePlacePhoto{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, false); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto object: %s", err)
	}

	AddGooglePlacePhotoHook(boil.BeforeInsertHook, googlePlacePhotoBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	googlePlacePhotoBeforeInsertHooks = []GooglePlacePhotoHook{}

	AddGooglePlacePhotoHook(boil.AfterInsertHook, googlePlacePhotoAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	googlePlacePhotoAfterInsertHooks = []GooglePlacePhotoHook{}

	AddGooglePlacePhotoHook(boil.AfterSelectHook, googlePlacePhotoAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	googlePlacePhotoAfterSelectHooks = []GooglePlacePhotoHook{}

	AddGooglePlacePhotoHook(boil.BeforeUpdateHook, googlePlacePhotoBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	googlePlacePhotoBeforeUpdateHooks = []GooglePlacePhotoHook{}

	AddGooglePlacePhotoHook(boil.AfterUpdateHook, googlePlacePhotoAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	googlePlacePhotoAfterUpdateHooks = []GooglePlacePhotoHook{}

	AddGooglePlacePhotoHook(boil.BeforeDeleteHook, googlePlacePhotoBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	googlePlacePhotoBeforeDeleteHooks = []GooglePlacePhotoHook{}

	AddGooglePlacePhotoHook(boil.AfterDeleteHook, googlePlacePhotoAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	googlePlacePhotoAfterDeleteHooks = []GooglePlacePhotoHook{}

	AddGooglePlacePhotoHook(boil.BeforeUpsertHook, googlePlacePhotoBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	googlePlacePhotoBeforeUpsertHooks = []GooglePlacePhotoHook{}

	AddGooglePlacePhotoHook(boil.AfterUpsertHook, googlePlacePhotoAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	googlePlacePhotoAfterUpsertHooks = []GooglePlacePhotoHook{}
}

func testGooglePlacePhotosInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := GooglePlacePhotos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGooglePlacePhotosInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(googlePlacePhotoColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := GooglePlacePhotos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGooglePlacePhotoToOneGooglePlaceUsingGooglePlace(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local GooglePlacePhoto
	var foreign GooglePlace

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, googlePlacePhotoDBTypes, false, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, googlePlaceDBTypes, false, googlePlaceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlace struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.GooglePlaceID = foreign.GooglePlaceID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.GooglePlace().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.GooglePlaceID != foreign.GooglePlaceID {
		t.Errorf("want: %v, got %v", foreign.GooglePlaceID, check.GooglePlaceID)
	}

	ranAfterSelectHook := false
	AddGooglePlaceHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *GooglePlace) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := GooglePlacePhotoSlice{&local}
	if err = local.L.LoadGooglePlace(ctx, tx, false, (*[]*GooglePlacePhoto)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.GooglePlace == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.GooglePlace = nil
	if err = local.L.LoadGooglePlace(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.GooglePlace == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testGooglePlacePhotoToOneGooglePlacePhotoReferenceUsingPhotoReferenceGooglePlacePhotoReference(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local GooglePlacePhoto
	var foreign GooglePlacePhotoReference

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, googlePlacePhotoDBTypes, false, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, googlePlacePhotoReferenceDBTypes, false, googlePlacePhotoReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhotoReference struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.PhotoReference = foreign.PhotoReference
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.PhotoReferenceGooglePlacePhotoReference().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.PhotoReference != foreign.PhotoReference {
		t.Errorf("want: %v, got %v", foreign.PhotoReference, check.PhotoReference)
	}

	ranAfterSelectHook := false
	AddGooglePlacePhotoReferenceHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *GooglePlacePhotoReference) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := GooglePlacePhotoSlice{&local}
	if err = local.L.LoadPhotoReferenceGooglePlacePhotoReference(ctx, tx, false, (*[]*GooglePlacePhoto)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.PhotoReferenceGooglePlacePhotoReference == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.PhotoReferenceGooglePlacePhotoReference = nil
	if err = local.L.LoadPhotoReferenceGooglePlacePhotoReference(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.PhotoReferenceGooglePlacePhotoReference == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testGooglePlacePhotoToOneSetOpGooglePlaceUsingGooglePlace(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a GooglePlacePhoto
	var b, c GooglePlace

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, googlePlacePhotoDBTypes, false, strmangle.SetComplement(googlePlacePhotoPrimaryKeyColumns, googlePlacePhotoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, googlePlaceDBTypes, false, strmangle.SetComplement(googlePlacePrimaryKeyColumns, googlePlaceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, googlePlaceDBTypes, false, strmangle.SetComplement(googlePlacePrimaryKeyColumns, googlePlaceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*GooglePlace{&b, &c} {
		err = a.SetGooglePlace(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.GooglePlace != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.GooglePlacePhotos[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.GooglePlaceID != x.GooglePlaceID {
			t.Error("foreign key was wrong value", a.GooglePlaceID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.GooglePlaceID))
		reflect.Indirect(reflect.ValueOf(&a.GooglePlaceID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.GooglePlaceID != x.GooglePlaceID {
			t.Error("foreign key was wrong value", a.GooglePlaceID, x.GooglePlaceID)
		}
	}
}
func testGooglePlacePhotoToOneSetOpGooglePlacePhotoReferenceUsingPhotoReferenceGooglePlacePhotoReference(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a GooglePlacePhoto
	var b, c GooglePlacePhotoReference

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, googlePlacePhotoDBTypes, false, strmangle.SetComplement(googlePlacePhotoPrimaryKeyColumns, googlePlacePhotoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, googlePlacePhotoReferenceDBTypes, false, strmangle.SetComplement(googlePlacePhotoReferencePrimaryKeyColumns, googlePlacePhotoReferenceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, googlePlacePhotoReferenceDBTypes, false, strmangle.SetComplement(googlePlacePhotoReferencePrimaryKeyColumns, googlePlacePhotoReferenceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*GooglePlacePhotoReference{&b, &c} {
		err = a.SetPhotoReferenceGooglePlacePhotoReference(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.PhotoReferenceGooglePlacePhotoReference != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.PhotoReferenceGooglePlacePhotos[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.PhotoReference != x.PhotoReference {
			t.Error("foreign key was wrong value", a.PhotoReference)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PhotoReference))
		reflect.Indirect(reflect.ValueOf(&a.PhotoReference)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.PhotoReference != x.PhotoReference {
			t.Error("foreign key was wrong value", a.PhotoReference, x.PhotoReference)
		}
	}
}

func testGooglePlacePhotosReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGooglePlacePhotosReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GooglePlacePhotoSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGooglePlacePhotosSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := GooglePlacePhotos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	googlePlacePhotoDBTypes = map[string]string{`ID`: `char`, `GooglePlaceID`: `varchar`, `PhotoReference`: `varchar`, `Width`: `int`, `Height`: `int`, `URL`: `varchar`, `CreatedAt`: `timestamp`, `UpdatedAt`: `timestamp`}
	_                       = bytes.MinRead
)

func testGooglePlacePhotosUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(googlePlacePhotoPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(googlePlacePhotoAllColumns) == len(googlePlacePhotoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := GooglePlacePhotos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testGooglePlacePhotosSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(googlePlacePhotoAllColumns) == len(googlePlacePhotoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &GooglePlacePhoto{}
	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := GooglePlacePhotos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, googlePlacePhotoDBTypes, true, googlePlacePhotoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(googlePlacePhotoAllColumns, googlePlacePhotoPrimaryKeyColumns) {
		fields = googlePlacePhotoAllColumns
	} else {
		fields = strmangle.SetComplement(
			googlePlacePhotoAllColumns,
			googlePlacePhotoPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := GooglePlacePhotoSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testGooglePlacePhotosUpsert(t *testing.T) {
	t.Parallel()

	if len(googlePlacePhotoAllColumns) == len(googlePlacePhotoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLGooglePlacePhotoUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := GooglePlacePhoto{}
	if err = randomize.Struct(seed, &o, googlePlacePhotoDBTypes, false); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert GooglePlacePhoto: %s", err)
	}

	count, err := GooglePlacePhotos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, googlePlacePhotoDBTypes, false, googlePlacePhotoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize GooglePlacePhoto struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert GooglePlacePhoto: %s", err)
	}

	count, err = GooglePlacePhotos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
