// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("GooglePlaceOpeningPeriods", testGooglePlaceOpeningPeriodsUpsert)

	t.Run("GooglePlacePhotoAttributions", testGooglePlacePhotoAttributionsUpsert)

	t.Run("GooglePlacePhotoReferences", testGooglePlacePhotoReferencesUpsert)

	t.Run("GooglePlacePhotos", testGooglePlacePhotosUpsert)

	t.Run("GooglePlaceReviews", testGooglePlaceReviewsUpsert)

	t.Run("GooglePlaceTypes", testGooglePlaceTypesUpsert)

	t.Run("GooglePlaces", testGooglePlacesUpsert)

	t.Run("Places", testPlacesUpsert)

	t.Run("PlanCandidatePlaces", testPlanCandidatePlacesUpsert)

	t.Run("PlanCandidateSetCategories", testPlanCandidateSetCategoriesUpsert)

	t.Run("PlanCandidateSetSearchedPlaces", testPlanCandidateSetSearchedPlacesUpsert)

	t.Run("PlanCandidateSets", testPlanCandidateSetsUpsert)

	t.Run("PlanCandidates", testPlanCandidatesUpsert)

	t.Run("Users", testUsersUpsert)
}
