package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"poroto.app/poroto/planner/graphql/model"
)

// LikeToPlace is the resolver for the likeToPlace field.
func (r *mutationResolver) LikeToPlace(ctx context.Context, input model.LikeToPlaceInput) (*model.LikeToPlaceOutput, error) {
	panic(fmt.Errorf("not implemented: LikeToPlace - likeToPlace"))
}
