wipe     = true
pkgname = "entities"
output = "internal/infrastructure/rdb/entities"
[mysql]
    dbname    = "poroto"
    host      = "localhost"
    port      = 3306
    user      = "root"
    pass      = "password"
    sslmode   = "false"
    blacklist = ["migrations", "goose_db_version", "google_places.location"]