templates = [
    "${GOPATH}/pkg/mod/github.com/volatiletech/sqlboiler/v4@<sqlboiler-version>/templates/main", # sqlboilerのテンプレートディレクトリ
    "${GOPATH}/pkg/mod/github.com/volatiletech/sqlboiler/v4@<sqlboiler-version>/templates/test",
    "db/extensions/templates/boilv4/mysql",
]

wipe     = true
pkgname = "generated"
output = "internal/infrastructure/rdb/generated"
no-tests = true
[mysql]
    dbname    = "poroto"
    host      = "localhost"
    port      = 3306
    user      = "root"
    pass      = "password"
    sslmode   = "false"
    blacklist = ["goose_db_version"]