package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"poroto.app/poroto/planner/internal/interface/graphql/model"
)

// LikedPlacesByUser is the resolver for the likedPlacesByUser field.
func (r *queryResolver) LikedPlacesByUser(ctx context.Context, input model.LikedPlacesByUserInput) (*model.LikedPlacesByUserOutput, error) {
	panic(fmt.Errorf("not implemented: LikedPlacesByUser - likedPlacesByUser"))
}
