package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.uber.org/zap"
	"poroto.app/poroto/planner/internal/domain/models"
	"poroto.app/poroto/planner/internal/domain/services/plan"
	"poroto.app/poroto/planner/internal/interface/graphql/factory"
	"poroto.app/poroto/planner/internal/interface/graphql/model"
)

// Plan is the resolver for the plan field.
func (r *queryResolver) Plan(ctx context.Context, input model.PlanInput) (*model.PlanOutput, error) {
	p, err := r.PlanService.FetchPlan(ctx, input.PlanID)
	if err != nil {
		return nil, fmt.Errorf("error while fetching plan: %v", err)
	}

	if p == nil {
		return nil, nil
	}

	graphqlPlan, err := factory.PlanFromDomainModel(*p, nil)
	if err != nil {
		r.Logger.Error("error while converting plan domain model to graphql model", zap.Error(err))
		return nil, fmt.Errorf("internal server error")
	}

	return &model.PlanOutput{
		Plan: graphqlPlan,
	}, nil
}

// Plans is the resolver for the plans field.
func (r *queryResolver) Plans(ctx context.Context, input *model.PlansInput) (*model.PlansOutput, error) {
	plans, nextPageToken, err := r.PlanService.FetchPlans(ctx, plan.FetchPlansInput{
		PageToken: input.PageToken,
		Limit:     input.Limit,
	})
	if err != nil {
		r.Logger.Error("error while fetching plans", zap.Error(err))
		return nil, fmt.Errorf("could not fetch plans")
	}

	return &model.PlansOutput{
		Plans:         factory.PlansFromDomainModel(plans, nil),
		NextPageToken: nextPageToken,
	}, nil
}

// PlansByLocation is the resolver for the plansByLocation field.
func (r *queryResolver) PlansByLocation(ctx context.Context, input model.PlansByLocationInput) (*model.PlansByLocationOutput, error) {
	plans, nextPageToken, err := r.PlanService.FetchPlansByLocation(
		ctx,
		models.GeoLocation{
			Latitude:  input.Latitude,
			Longitude: input.Longitude,
		},
		input.Limit,
	)
	if err != nil {
		r.Logger.Error("error while fetching plans by location", zap.Error(err))
		return nil, fmt.Errorf("internal server error")
	}

	return &model.PlansByLocationOutput{
		Plans:   factory.PlansFromDomainModel(plans, nil),
		PageKey: nextPageToken,
	}, nil
}

// PlansByUser is the resolver for the plansByUser field.
func (r *queryResolver) PlansByUser(ctx context.Context, input model.PlansByUserInput) (*model.PlansByUserOutput, error) {
	author, err := r.UserService.FindByUserId(ctx, input.UserID)
	if err != nil {
		r.Logger.Error("error while fetching user by id", zap.Error(err))
		return nil, fmt.Errorf("internal server error")
	}

	if author == nil {
		return nil, nil
	}

	plans, err := r.PlanService.PlansByUser(ctx, input.UserID)
	if err != nil {
		r.Logger.Error("error while fetching plans by user", zap.Error(err))
		return nil, fmt.Errorf("internal server error")
	}

	return &model.PlansByUserOutput{
		Plans:  factory.PlansFromDomainModel(plans, nil),
		Author: factory.UserFromDomainModel(author),
	}, nil
}
