package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"poroto.app/poroto/planner/internal/interface/graphql/model"
)

// UploadPhotoToPlaceInPlan is the resolver for the uploadPhotoToPlaceInPlan field.
func (r *mutationResolver) UploadPhotoToPlaceInPlan(ctx context.Context, input model.UploadPhotoToPlaceInPlanInput) (*model.UploadPhotoToPlaceInPlanOutput, error) {
	panic(fmt.Errorf("not implemented: UploadPhotoToPlaceInPlan - uploadPhotoToPlaceInPlan"))
}
