name: build
run-name: Build by @${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup_environment
      - name: Build
        run: go build -v ./...
  lint:
    - runs-on: ubuntu-latest
    - steps:
      - uses: ./.github/actions/setup_environment
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.0
          golangci-lint --version
      - name: Run golangci-lint
        run: golangci-lint run
  test:
    - runs-on: ubuntu-latest
    - steps:
      - uses: ./.github/actions/setup_environment
    - name: Test
      run: go test -v ./...

    - name: Upload Go test results
      uses: actions/upload-artifact@v3
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json
