name: deploy
run-name: Deploy by @${{ github.actor }}
on:
  push:
    branches:
      - master

jobs:
  # SEE: https://github.com/google-github-actions/deploy-appengine
  deploy:
    name: GAE deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/decrypt_secrets
        with:
          google_credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          gh_personal_access_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      # SEE: https://github.com/google-github-actions/deploy-appengine#authorization
      - name: Deploy an App Engine app
        uses: google-github-actions/deploy-appengine@v1