name: deploy
run-name: Deploy by @${{ github.actor }}
on: push
#  push:
#    branches:
#      - master

jobs:
  build:
    uses: ./.github/workflows/build_workflow.yaml
  # SEE: https://github.com/google-github-actions/deploy-appengine
  deploy:
    needs: build
    name: GAE deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/decrypt_secrets
        with:
          google_credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          gh_personal_access_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      # SEE: https://github.com/google-github-actions/deploy-appengine#authorization
      - name: Deploy an App Engine app
        uses: google-github-actions/deploy-appengine@v1