name: graphql codegen
run-name: GraphQL Codegen by @${{ github.actor }}
on: [ push ]
jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_environment
      - name: Codegen
        run: go generate ./...
  check-codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_environment
      - name: Codegen
        run: go generate ./...
      - name: Check diff
        run: git diff --exit-code