name: create-deploy-request
run-name: Creating PlanetScale Deploy Request by @${{ github.actor }}
on:
  pull_request:
    branches: [main]
    paths: ["db/migrations/**"]

jobs:
  # SEE: https://planetscale.com/blog/announcing-the-planetscale-github-actions
  merge-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Create a deploy request
        uses: planetscale/create-deploy-request-action@v2
        id: create_deploy_request
        with:
          org_name: poroto
          database_name: poroto
          branch_name: staging
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      - name: Deploy a deploy request
        uses: planetscale/deploy-deploy-request-action@v4
        with:
          org_name: poroto
          database_name: poroto
          number: ${{ steps.create_deploy_request.outputs.number }}
          wait: true
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}